---
# --> (Example) Create an IngressRoute for your service...
 apiVersion: traefik.io/v1alpha1
 kind: IngressRoute
 metadata:
   name: vault-ingressroute-gui  # <-- Replace with your IngressRoute name
   namespace: vault # <-- Replace with your namespace
 spec:
   entryPoints:
   - websecure
   routes:
   - match: Host(`vault.equipement.gov.ma`)  # <-- Replace with your FQDN
     kind: Rule
     services:
     - name: hashi-vault-prod-ui  # <-- Replace with your service name
       port: 8200
   tls:
     certResolver: default
